// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createMockSupabaseClient() {
  console.warn("[Supabase] Environment variables missing — running in-memory mock client");

  type MockSession = {
    access_token: string;
    refresh_token: string;
    expires_in: number;
    token_type: string;
    user: {
      id: string;
      email: string;
      is_anonymous: boolean;
      app_metadata: Record<string, unknown>;
      user_metadata: Record<string, unknown>;
      aud: string;
      created_at: string;
    };
  };

  let currentSession: MockSession | null = {
    access_token: "mock-access-token",
    refresh_token: "mock-refresh-token",
    expires_in: 3600,
    token_type: "bearer",
    user: {
      id: "mock-anon-user-" + Math.random().toString(36).slice(2, 8),
      email: "",
      is_anonymous: true,
      app_metadata: {},
      user_metadata: { full_name: "Guest Scientist" },
      aud: "authenticated",
      created_at: new Date().toISOString(),
    },
  };

  const authListeners = new Set<(event: string, session: MockSession | null) => void>();
  const storageMap = new Map<string, string>();
  const tables = new Map<string, Record<string, unknown>[]>();

  function getTable(name: string): Record<string, unknown>[] {
    if (!tables.has(name)) {
      tables.set(name, []);
    }
    return tables.get(name)!;
  }

  function createQueryBuilder(table: string) {
    let rows = [...getTable(table)];
    let isCountHead = false;
    let isSingle = false;

    type QueryBuilder = {
      select: (fields?: string, opts?: { count?: string; head?: boolean }) => QueryBuilder;
      eq: (col: string, val: unknown) => QueryBuilder;
      is: (col: string, val: unknown) => QueryBuilder;
      gte: (col: string, val: unknown) => QueryBuilder;
      order: (col: string, opts?: { ascending?: boolean }) => QueryBuilder;
      limit: (n: number) => QueryBuilder;
      maybeSingle: () => QueryBuilder;
      single: () => QueryBuilder;
      insert: (
        newRows: Record<string, unknown> | Record<string, unknown>[],
      ) => Promise<{ data: unknown; error: null }>;
      update: (
        updates: Record<string, unknown>,
      ) => Promise<{ eq: (col: string, val: unknown) => Promise<{ data: unknown; error: null }> }>;
      then: <TResult1 = unknown, TResult2 = never>(
        onfulfilled?:
          | ((value: {
              data: unknown;
              count: number;
              error: null;
            }) => TResult1 | PromiseLike<TResult1>)
          | null,
        onrejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null,
      ) => Promise<TResult1 | TResult2>;
    };

    const builder: QueryBuilder = {
      select(_fields?: string, opts?: { count?: string; head?: boolean }) {
        if (opts?.head) {
          isCountHead = true;
        }
        return builder;
      },
      eq(col: string, val: unknown) {
        rows = rows.filter((r) => r[col] === val);
        return builder;
      },
      is(col: string, val: unknown) {
        rows = rows.filter((r) => (val === null ? r[col] == null : r[col] === val));
        return builder;
      },
      gte(col: string, val: unknown) {
        rows = rows.filter((r) => (r[col] as string | number) >= (val as string | number));
        return builder;
      },
      order(col: string, opts?: { ascending?: boolean }) {
        const asc = opts?.ascending !== false;
        rows.sort((a, b) => {
          const valA = a[col] as string | number;
          const valB = b[col] as string | number;
          if (valA < valB) return asc ? -1 : 1;
          if (valA > valB) return asc ? 1 : -1;
          return 0;
        });
        return builder;
      },
      limit(n: number) {
        rows = rows.slice(0, n);
        return builder;
      },
      maybeSingle() {
        isSingle = true;
        return builder;
      },
      single() {
        isSingle = true;
        return builder;
      },
      async insert(newRows: Record<string, unknown> | Record<string, unknown>[]) {
        const arr = Array.isArray(newRows) ? newRows : [newRows];
        const tableArr = getTable(table);
        const inserted = arr.map((item) => {
          const row = {
            id:
              (item["id"] as string) ||
              `${table}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
            created_at: (item["created_at"] as string) || new Date().toISOString(),
            ...item,
          };
          tableArr.push(row);
          return row;
        });
        return { data: Array.isArray(newRows) ? inserted : inserted[0], error: null };
      },
      async update(updates: Record<string, unknown>) {
        return {
          eq(col: string, val: unknown) {
            const tableArr = getTable(table);
            for (const r of tableArr) {
              if (r[col] === val) {
                Object.assign(r, updates);
              }
            }
            return Promise.resolve({ data: updates, error: null });
          },
        };
      },
      // Make builder thenable
      then(onfulfilled, onrejected) {
        const count = rows.length;
        const resultData = isCountHead ? null : isSingle ? (rows[0] ?? null) : rows;
        return Promise.resolve({ data: resultData, count, error: null }).then(
          onfulfilled,
          onrejected,
        );
      },
    };

    return builder;
  }

  return {
    auth: {
      async getSession() {
        return { data: { session: currentSession }, error: null };
      },
      async getUser() {
        return { data: { user: currentSession?.user ?? null }, error: null };
      },
      async signInAnonymously() {
        if (!currentSession) {
          currentSession = {
            access_token: "mock-access-token",
            refresh_token: "mock-refresh-token",
            expires_in: 3600,
            token_type: "bearer",
            user: {
              id: "mock-anon-user-" + Math.random().toString(36).slice(2, 8),
              email: "",
              is_anonymous: true,
              app_metadata: {},
              user_metadata: { full_name: "Guest Scientist" },
              aud: "authenticated",
              created_at: new Date().toISOString(),
            },
          };
        }
        for (const l of authListeners) l("SIGNED_IN", currentSession);
        return { data: { session: currentSession, user: currentSession.user }, error: null };
      },
      onAuthStateChange(cb: (event: string, session: MockSession | null) => void) {
        authListeners.add(cb);
        setTimeout(() => cb(currentSession ? "SIGNED_IN" : "INITIAL_SESSION", currentSession), 0);
        return {
          data: {
            subscription: {
              unsubscribe: () => authListeners.delete(cb),
            },
          },
        };
      },
      async signUp({
        email,
        options,
      }: {
        email: string;
        options?: { data?: { full_name?: string } };
      }) {
        currentSession = {
          access_token: "mock-access-token",
          refresh_token: "mock-refresh-token",
          expires_in: 3600,
          token_type: "bearer",
          user: {
            id: "mock-user-" + Math.random().toString(36).slice(2, 8),
            email,
            is_anonymous: false,
            app_metadata: {},
            user_metadata: options?.data || {},
            aud: "authenticated",
            created_at: new Date().toISOString(),
          },
        };
        for (const l of authListeners) l("SIGNED_IN", currentSession);
        return { data: { user: currentSession.user, session: currentSession }, error: null };
      },
      async signInWithPassword({ email }: { email: string }) {
        currentSession = {
          access_token: "mock-access-token",
          refresh_token: "mock-refresh-token",
          expires_in: 3600,
          token_type: "bearer",
          user: {
            id: "mock-user-" + Math.random().toString(36).slice(2, 8),
            email,
            is_anonymous: false,
            app_metadata: {},
            user_metadata: {},
            aud: "authenticated",
            created_at: new Date().toISOString(),
          },
        };
        for (const l of authListeners) l("SIGNED_IN", currentSession);
        return { data: { user: currentSession.user, session: currentSession }, error: null };
      },
      async signOut() {
        currentSession = null;
        for (const l of authListeners) l("SIGNED_OUT", null);
        return { error: null };
      },
      async updateUser({
        email,
        password,
        data,
      }: {
        email?: string;
        password?: string;
        data?: Record<string, unknown>;
      }) {
        if (currentSession) {
          if (email) currentSession.user.email = email;
          if (data) Object.assign(currentSession.user.user_metadata, data);
          currentSession.user.is_anonymous = false;
        }
        for (const l of authListeners) l("USER_UPDATED", currentSession);
        return { data: { user: currentSession?.user }, error: null };
      },
      async linkIdentity() {
        return { data: {}, error: null };
      },
      async setSession(_tokens: unknown) {
        return { data: { session: currentSession }, error: null };
      },
    },
    from(table: string) {
      return createQueryBuilder(table);
    },
    storage: {
      from(bucket: string) {
        return {
          async upload(path: string, blob: unknown) {
            let url = "";
            if (typeof blob === "string") {
              url = blob;
            } else if (typeof window !== "undefined" && blob instanceof Blob) {
              url = URL.createObjectURL(blob);
            }
            storageMap.set(`${bucket}:${path}`, url);
            return { data: { path }, error: null };
          },
          async createSignedUrl(path: string, _expiresIn: number) {
            const url = storageMap.get(`${bucket}:${path}`) || path;
            return { data: { signedUrl: url }, error: null };
          },
        };
      },
    },
    async rpc(fn: string, params: Record<string, unknown>) {
      if (fn === "create_generation") {
        const row = {
          id: "gen-" + Date.now() + "-" + Math.random().toString(36).slice(2, 6),
          user_id: params?.["p_user_id"] || currentSession?.user?.id || "anon-user",
          parent_generation_id: params?.["p_parent_generation_id"] || null,
          title: params?.["p_title"] || "",
          source_text: params?.["p_source_text"] || "",
          image_path: params?.["p_image_path"] || null,
          created_at: new Date().toISOString(),
        };
        getTable("generations").push(row);
        return { data: row, error: null };
      }
      return { data: null, error: null };
    },
  } as unknown as ReturnType<typeof createClient<Database>>;
}

function createSupabaseClient() {
  // The platform-managed VITE_SUPABASE_URL can point at a stale project; derive
  // the URL from the project ID (which is kept in sync) when they disagree.
  const projectId =
    import.meta.env["VITE_SUPABASE_PROJECT_ID"] || process.env["SUPABASE_PROJECT_ID"];
  const envUrl = import.meta.env["VITE_SUPABASE_URL"] || process.env["SUPABASE_URL"];
  const SUPABASE_URL =
    projectId && envUrl && !envUrl.includes(projectId)
      ? `https://${projectId}.supabase.co`
      : envUrl;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] || process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    return createMockSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
